apps/proyectos/suscripciones_pagos/cuenta/urls.py
from django.urls import path
from apps.proyectos.suscripciones_pagos.cuenta import views
from .views import LoginUsuarioView

app_name = "cuenta"

urlpatterns = [
    #login
    path("login/", views.login, name="login"),
    path("login_usuario/", LoginUsuarioView.as_view(), name="login_usuario"),
    #registro
    path("registro/", views.registro, name="registro"),
    path("registro_usuario/", views.registro_usuario, name="registro_usuario"),
    #logout
    path("logout/", views.logout_view, name="logout"),
]

apps/proyectos/suscripciones_pagos/precios_suscripcion/urls.py
from django.urls import path, include
from apps.proyectos.suscripciones_pagos.precios_suscripcion import views

app_name= 'precios_suscripcion'

urlpatterns = [
    path("", views.index, name="index"),
]

portafolio_david/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.portafolio.urls", namespace='portafolio')),
    #proyecto suscripciones
    path("suscripciones/", include("apps.proyectos.suscripciones_pagos.precios_suscripcion.urls", namespace='precios')),
    path("cuenta/", include("apps.proyectos.suscripciones_pagos.cuenta.urls", namespace="cuenta")),
]

apps/proyectos/suscripciones_pagos/cuenta/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import BaseUserManager
from django.db import models

# Create your models here.
class UserManager(BaseUserManager):

    def create_user(self, email, name, password=None, **extra_fields):
        if not email:
            raise ValueError('El usuario debe tener un email')

        email = self.normalize_email(email)
        user = self.model(email=email, name=name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser debe tener is_staff=True.')

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser debe tener is_superuser=True.')

        return self.create_user(email, name, password, **extra_fields)
    
class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, max_length=254)
    name = models.CharField(max_length=150)

    fecha_creacion = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

    objects = UserManager()

    def __str__(self):
        return self.email
    

apps/proyectos/suscripciones_pagos/precios_suscripcion/models.py
from django.db import models

# Create your models here.
class Suscripcion(models.Model):
    nombre = models.CharField(max_length=100)
    descripcion = models.TextField()
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    
    activa = models.BooleanField(default=True)
    
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.nombre} - ${self.precio}"

apps/proyectos/suscripciones_pagos/suscripciones/models.py
from django.db import models
from apps.proyectos.suscripciones_pagos.precios_suscripcion.models import Suscripcion
from datetime import timedelta
from django.utils import timezone
from django.conf import settings

class UsuarioSuscripcion(models.Model):
    ESTADOS = (
        ('activa', 'Activa'),
        ('vencida', 'Vencida'),
        ('cancelada', 'Cancelada'),
    )

    usuario = models.ForeignKey(
    settings.AUTH_USER_MODEL,
    on_delete=models.CASCADE
    )
    suscripcion = models.ForeignKey(Suscripcion, on_delete=models.CASCADE)

    fecha_inicio = models.DateTimeField(default=timezone.now)
    fecha_vencimiento = models.DateTimeField()

    estado = models.CharField(max_length=20, choices=ESTADOS, default='activa')
    pagado = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        # Si no tiene fecha de vencimiento la calculamos
        if not self.fecha_vencimiento:
            self.fecha_vencimiento = self.fecha_inicio + timedelta(days=30)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.usuario.username} - {self.suscripcion.nombre}"

apps/proyectos/suscripciones_pagos/cuenta/views.py
from django.shortcuts import render, redirect
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import AllowAny
from django.contrib.auth import get_user_model
from rest_framework.views import APIView
from rest_framework.response import Response
from django.contrib.auth import authenticate
from rest_framework import status
from rest_framework import generics
from apps.proyectos.suscripciones_pagos.cuenta.models import User
from django.contrib.auth import login as auth_login
from .serializers import LoginSerializer
from django.contrib.auth import logout


#json
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

User = get_user_model()

# VISTAS HTML
def login(request):
    return render(request, "proyectos/pagina_suscripciones/login.html")

def registro(request):
    return render(request, "proyectos/pagina_suscripciones/registro.html")

#registro
@csrf_exempt
def registro_usuario(request):
    print("ENTRÓ A LA VISTA")
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            print("DATA RECIBIDA:", data)

            name = data.get("name")
            email = data.get("email")
            password = data.get("password")

            if not name or not email or not password:
                print("error de campos")
                return JsonResponse({"error": "Todos los campos son obligatorios"}, status=400)

            if User.objects.filter(email=email).exists():
                print("error de email")
                return JsonResponse({"error": "Usuario ya existe"}, status=400)

            User.objects.create_user(
                email=email,
                name=name,
                password=password
            )
            print(f"creo usuario: {name}")
            return JsonResponse({"message": "Usuario creado correctamente"}, status=201)

        except Exception as e:
            print(e)
            return JsonResponse({"error": str(e)}, status=400)

    return JsonResponse({"error": "Método no permitido"}, status=405)

#logout
def logout_view(request):
    logout(request)
    return redirect("cuenta:login") 

# API LOGIN
class LoginUsuarioView(APIView):

    def post(self, request):
        serializer = LoginSerializer(data=request.data)

        if serializer.is_valid():
            user = serializer.validated_data["user"]

            # Inicia sesión correctamente
            auth_login(request, user)

            return Response(
                {"message": "Login exitoso", "redirect_url": "proyectos/pagina_suscripciones/index.html"},
                status=status.HTTP_200_OK,
                
            )
        print("USER AUTHENTICATED:", request.user.is_authenticated)

        return Response(
            serializer.errors,
            status=status.HTTP_400_BAD_REQUEST
        )

apps/proyectos/suscripciones_pagos/precios_suscripcion/views.py
from django.shortcuts import render
from apps.proyectos.suscripciones_pagos.precios_suscripcion.models import Suscripcion

# Create your views here.
def index(request):
    suscripciones = Suscripcion.objects.all()
    return render(request, "proyectos/pagina_suscripciones/index.html", {"suscripciones": suscripciones})

apps/proyectos/suscripciones_pagos/suscripciones/views.py
from django.shortcuts import render

# Create your views here.

templates/proyectos/pagina_suscripciones/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static "assets/favicon_suscripciones.ico" %}" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

        <!-- Font Awesome -->
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        rel="stylesheet"
        />
        <!-- Google Fonts -->
        <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
        />
        <!-- MDB -->
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/9.3.0/mdb.min.css"
        rel="stylesheet"
        />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "css/styles_suscripciones.css" %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        {% include "proyectos/pagina_suscripciones/navbar.html" %}
        <!-- Page Content-->
        {% block contenido %}{% endblock contenido %}
        <!-- Footer-->
        {% include "blocks/footer.html" %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static "js/scripts_suscripciones.js" %}"></script>
        <!-- MDB -->
        <script
        type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/9.3.0/mdb.umd.min.js"
        ></script>
        {% block scripts %}{% endblock scripts %}
    </body>
</html>

templates/proyectos/pagina_suscripciones/index.html
{% extends "proyectos/pagina_suscripciones/base.html" %}
{% load static %}

{% block contenido %}
    <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-5"><img class="img-fluid rounded mb-4 mb-lg-0" src="{% static "assets/proyecto_suscripciones.png" %}" style="width: 100%" /></div>
                <div class="col-lg-7">
                    <h1 class="font-weight-light">Suscripción Premium: Acceso Ilimitado</h1>
                    <p>Desbloquea herramientas exclusivas para potenciar tu carrera como desarrollador. Únete a nuestra comunidad y accede a contenido especializado, mentorías y recursos descargables cada mes.</p>
                    <a class="btn btn-primary" href="{% url "cuenta:login" %}">¡Empieza Ahora!</a> <!--Esto ira al inicio de sesion-->
                </div>
            </div>
            <!-- Call to Action-->
            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="card-body"><p class="text-white m-0">Elige el plan que mejor se adapte a tus metas profesionales y comienza hoy mismo.</p></div>
            </div>
            <!-- Content Row-->
            <!--los planes se haran por admin, por lo que solo se necesita una tarjeta de boceto-->
            <div class="row gx-4 gx-lg-5">
                {% for suscripcion in suscripciones %}
                <div class="col-md-4 mb-5">
                    <div class="card h-100">
                        <div class="card-body">
                            <h2 class="card-title">{{suscripcion.nombre}}</h2>
                            <p class="card-text">{{suscripcion.descripcion}}</p>
                        </div>
                        <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">Suscribirme</a></div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock contenido %}

templates/proyectos/pagina_suscripciones/login.html
{% extends "proyectos/pagina_suscripciones/base.html" %}
{% load static %}

{% block contenido %}
<div class="container px-8 px-lg-5" style="padding: 8% 10%">
    <h1>INICIO DE SESION</h1><br><br>
    <form id="loginForm">
        {% csrf_token %}
        <!-- Email input -->
        <div data-mdb-input-init class="form-outline mb-4">
            <input type="email" id="email" class="form-control" />
            <label class="form-label" for="form2Example1">Email</label>
        </div>

        <!-- Password input -->
        <div data-mdb-input-init class="form-outline mb-4">
            <input type="password" id="password" class="form-control" />
            <label class="form-label" for="form2Example2">Contraseña</label>
        </div>

        <!-- Submit button -->
        <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Ingresar</button>

        <!-- Register buttons -->
        <div class="text-center">
            <p>No tienes cuenta?<a href="{% url "cuenta:registro" %}"> Registrate ahora</a></p>
        </div>
    </form>
</div>
{% endblock contenido %}

{% block scripts %}
<script>

function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== "") {
        const cookies = document.cookie.split(";");
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + "=")) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

document.getElementById("loginForm").addEventListener("submit", function(e) {
    e.preventDefault();

    const email = document.getElementById("email").value;
    const password = document.getElementById("password").value;

    fetch("/cuenta/login_usuario/", {
        method: "POST",
        credentials: "same-origin",
        headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": getCookie("csrftoken")
        },
        body: JSON.stringify({
            email: email,
            password: password
        })
    })
    .then(response => {
        return response.json().then(data => ({
            status: response.status,
            body: data
        }));
    })
    .then(res => {

        if (res.status === 200) {
            alert(res.body.message);
            window.location.href = res.body.redirect_url;
        } else {
            alert(res.body.non_field_errors || "Error en login");
        }

    });

});
</script>
{% endblock scripts %}

templates/proyectos/pagina_suscripciones/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">Proyecto Suscripciones</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url "precios_suscripcion:index" %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="#!">Pagos</a></li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url "cuenta:logout" %}">Cerrar sesion</a></li>
                            <li class="nav-item" style="color: white; padding: 0.5rem 1rem;">{{request.user.name}}</li>
                        {% elif not request.user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url "cuenta:login" %}">Iniciar sesion</a></li> <!--o registar eso luego se realiza-->
                            <li class="nav-item"><a class="nav-link" href="{% url "cuenta:registro" %}">Registrarse</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

templates/proyectos/pagina_suscripciones/registro.html
{% extends "proyectos/pagina_suscripciones/base.html" %}
{% load static %}

{% block contenido %}
<div class="container px-8 px-lg-5" style="padding: 8% 10%">
    <h1>REGISTRAR</h1><br><br>
    <form id="registerForm">
        {% csrf_token %}
        <!-- Name input -->
        <div data-mdb-input-init class="form-outline mb-4">
            <input type="text" id="name" class="form-control" />
            <label  class="form-label" for="form2Example2">Usuario</label>
        </div>
        <div data-mdb-input-init class="form-outline mb-4">
            <input type="email" id="email" class="form-control" />
            <label  class="form-label" for="form2Example2">Email</label>
        </div>

        <div data-mdb-input-init class="form-outline mb-4">
            <input type="password" id="password" class="form-control" />
            <label class="form-label" for="form2Example2">Contraseña</label>
        </div>

        <div data-mdb-input-init class="form-outline mb-4">
            <input type="password" id="password2" class="form-control" />
            <label class="form-label" for="form2Example2">Confirmar Contraseña</label>
        </div>
        <!-- Submit button -->
        <button  type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Registrar</button>
        <button 
            type="button" 
            onclick="window.location.href='{% url 'cuenta:login' %}'"
            class="btn btn-primary btn-block mb-4">
            Cancelar</button>    
    </form>
    <p id="mensaje"></p>
</div>
{% endblock contenido %}
{% block scripts %}
<script>
    function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
document.getElementById("registerForm").addEventListener("submit", function(e) {
    e.preventDefault();

    const name = document.getElementById("name").value;
    const email = document.getElementById("email").value;
    const password = document.getElementById("password").value;
    const password2 = document.getElementById("password2").value;

    if (password !== password2) {
        alert("Las contraseñas no coinciden");
        return;
    }


    fetch("/cuenta/registro_usuario/", {
    method: "POST",
    credentials: "same-origin",
    headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": getCookie("csrftoken")
    },
    body: JSON.stringify({
        name: name,
        email: email,
        password: password,
        password2: password2
    })
    })
    .then(response => {
        return response.json().then(data => ({
            status: response.status,
            body: data
        }));
    })
    .then(res => {

        if (res.status === 201) {
            alert(res.body.message);
            window.location.href = "/cuenta/login/";
        } else {
            alert(res.body.error);
        }

    });
});
</script>
{% endblock scripts %}