apps/portafolio/urls.py
from django.urls import path
from apps.portafolio import views

app_name= 'portafolio'

urlpatterns = [
    path("", views.index, name="inicio"),
    path("contacto/", views.contact, name="contacto"),
    path("respuesta/", views.contact_ajax, name="contact_ajax"),
    path("proyectos/", views.projects, name="proyectos"),
    path("resumen/", views.resumen, name="resumen"),
    #descargar CV
    path('download-cv/', views.download_cv, name='download_cv'),
]

portafolio_david/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("apps.portafolio.urls", namespace='portafolio')),
    #proyecto suscripciones
    path("suscripciones/", include("apps.proyectos.suscripciones_pagos.precios_suscripcion.urls", namespace='precios')),
    path("cuenta/", include("apps.proyectos.suscripciones_pagos.cuenta.urls", namespace="cuenta")),
]

apps/portafolio/views.py
from django.shortcuts import render
from django.http import FileResponse, Http404
import os
from django.conf import settings
from django.core.mail import send_mail
from django.http import JsonResponse


# Create your views here.
def index(request):
    return render(request, "portafolio/index.html")

def contact(request):
    return render(request, "portafolio/contact.html")

def contact_ajax(request):

    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")

        if not name or not email or not message:
            return JsonResponse({
                "success": False,
                "error": "Todos los campos son obligatorios"
            })

        send_mail(
            subject="Nuevo mensaje desde tu portafolio",
            message=f"Nombre: {name}\nCorreo: {email}\n\nMensaje:\n{message}",
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=["davidalejandro241916@gmail.com"],
        )

        return JsonResponse({"success": True})

    return JsonResponse({"success": False}, status=400)

def projects(request):
    return render(request, "portafolio/projects.html")

def resumen(request):
    return render(request, "portafolio/resumen.html")

#descargar CV
def download_cv(request):
    file_path = os.path.join(
        settings.BASE_DIR,
        'static',
        'docs',
        'CV_Desarrollador_Backend_Junior_David_Cortes.pdf'
    )

    if not os.path.exists(file_path):
        raise Http404("El archivo no existe")

    return FileResponse(open(file_path, 'rb'), as_attachment=True)

templates/portafolio/contact.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content />
        <meta name="author" content />
        <title>Modern Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.ico" %}" />
        <!-- Custom Google font-->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "css/styles.css" %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url "portafolio:inicio" %}"><span class="fw-bolder text-primary">David Cortes</span></a> <!--hay que agregar ruta con django-->
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                            <li class="nav-item"><a class="nav-link" href="{% url "portafolio:inicio" %}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url "portafolio:resumen" %}">Resumen</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url "portafolio:proyectos" %}">Proyectos</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url "portafolio:contacto" %}">Contactos</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Contact form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                            <h1 class="fw-bolder">Escribeme un Email</h1>
                            <p class="lead fw-normal text-muted mb-0">Ayudame a crecer trabajando juntos!</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
                            <div class="col-lg-8 col-xl-6">
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- * * SB Forms Contact Form * *-->
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- This form is pre-integrated with SB Forms.-->
                                <!-- To make this form functional, sign up at-->
                                <!-- https://startbootstrap.com/solution/contact-forms-->
                                <!-- to get an API token!-->
                                <form id="contactForm">
                                    {% csrf_token %}
                                    <!-- Name input-->
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="name" name="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                        <label for="name">Nombre empresa/persona</label>
                                        <div class="invalid-feedback" data-sb-feedback="name:required">El nombre es requerido</div>
                                    </div>
                                    <!-- Email address input-->
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="email" name="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                                        <label for="email">Email</label>
                                        <div class="invalid-feedback" data-sb-feedback="email:required">El Email es requerido</div>
                                        <div class="invalid-feedback" data-sb-feedback="email:email">Email no valido</div>
                                    </div>
                                    <!-- Message input-->
                                    <div class="form-floating mb-3">
                                        <textarea class="form-control" id="message" name="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                                        <label for="message">Mensaje</label>
                                        <div class="invalid-feedback" data-sb-feedback="message:required">El mensaje es requerido</div>
                                    </div>
                                    <!-- Submit success message-->
                                    <!---->
                                    <!-- This is what your users will see when the form-->
                                    <!-- has successfully submitted-->
                                    {% if success %}
                                    <div class="alert alert-success">
                                        ¡Mensaje enviado correctamente!
                                    </div>
                                    {% endif %}
                                    <!-- Submit error message-->
                                    <!---->
                                    <!-- This is what your users will see when there is-->
                                    <!-- an error submitting the form-->
                                    <!-- Submit Button-->
                                    <div class="d-grid"><button class="btn btn-primary btn-lg" id="submitButton" type="submit">Enviar</button></div>
                                    <!--si acaso agregar boton de espera-->
                                </form>
                                <div id="formMessage" class="mt-3"></div>
                                </div></div>
                                </div>
                            </div>
                        </div><br>
                    </div>
                </div>
                <div class="container px-5">
                    <!-- Contact form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <h1 class="fw-bolder">Escribir al whatsapp</h1><br>
                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 mb-3"><a href="https://wa.link/yffq26" target="_blank" class="text-white"><i class="bi bi-whatsapp"></i></a></div>
                            <p class="lead fw-normal text-muted mb-0">O puedes llamar al +57 313 346 8413</p>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        {% include "blocks/footer.html" %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script>
        document.addEventListener("DOMContentLoaded", function () {

            const form = document.getElementById("contactForm");
            const msg = document.getElementById("formMessage");

            form.addEventListener("submit", function(e) {
                e.preventDefault();

                const formData = new FormData(form);

                fetch("{% url 'portafolio:contact_ajax' %}", {
                    method: "POST",
                    headers: {
                        "X-CSRFToken": formData.get("csrfmiddlewaretoken")
                    },
                    body: formData
                })
                .then(res => res.json())
                .then(data => {
                    if (data.success) {
                        msg.innerHTML = `
                            <div class="alert alert-success">
                                ¡Mensaje enviado correctamente!
                            </div>
                        `;
                        form.reset();
                    } else {
                        msg.innerHTML = `
                            <div class="alert alert-danger">
                                Error al enviar
                            </div>
                        `;
                    }
                })
                .catch(() => {
                    msg.innerHTML = `
                        <div class="alert alert-danger">
                            Error de conexión
                        </div>
                    `;
                });
            });

        });
        </script>
        <!-- Core theme JS-->
        <script src="{% static "js/scripts.js" %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    </body>
</html>

templates/portafolio/projects.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Modern Business - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static "assets/favicon.ico" %}" />
        <!-- Custom Google font-->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "css/styles.css" %}" rel="stylesheet" />
    </head>
    <body class="d-flex flex-column h-100 bg-light">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url "portafolio:inicio" %}"><span class="fw-bolder text-primary">David Cortes</span></a> <!--hay que agregar ruta con django-->
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                            <li class="nav-item"><a class="nav-link" href="{% url "portafolio:inicio" %}">Inicio</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url "portafolio:resumen" %}">Resumen</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url "portafolio:proyectos" %}">Proyectos</a></li>
                            <li class="nav-item"><a class="nav-link" href="{% url "portafolio:contacto" %}">Contactos</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Projects Section-->
            <section class="py-5">
                <div class="container px-5 mb-5">
                    <div class="text-center mb-5">
                        <h1 class="display-5 fw-bolder mb-0"><span class="text-gradient d-inline">Proyectos</span></h1>
                    </div>
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-11 col-xl-9 col-xxl-8">
                            <!-- Project Card 1-->
                            <div class="card overflow-hidden shadow rounded-4 border-0 mb-5">
                                <div class="card-body p-0">
                                    <div class="d-flex align-items-center">
                                        <div class="p-5">
                                            <h2 class="fw-bolder">Project Name 1</h2>
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius at enim eum illum aperiam placeat esse? Mollitia omnis minima saepe recusandae libero, iste ad asperiores! Explicabo commodi quo itaque! Ipsam!</p>
                                        </div>
                                        <img class="img-fluid" src="https://dummyimage.com/300x400/343a40/6c757d" alt="..." />
                                    </div>
                                </div>
                            </div>
                            <!-- Project Card 2-->
                            <div class="card overflow-hidden shadow rounded-4 border-0">
                                <div class="card-body p-0">
                                    <div class="d-flex align-items-center">
                                        <div class="p-5">
                                            <h2 class="fw-bolder">Project Name 2</h2>
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius at enim eum illum aperiam placeat esse? Mollitia omnis minima saepe recusandae libero, iste ad asperiores! Explicabo commodi quo itaque! Ipsam!</p>
                                        </div>
                                        <img class="img-fluid" src="https://dummyimage.com/300x400/343a40/6c757d" alt="..." />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Call to action section-->
            <section class="py-5 bg-gradient-primary-to-secondary text-white">
                <div class="container px-5 my-5">
                    <div class="text-center">
                        <h2 class="display-4 fw-bolder mb-4">¿Te interesa mi trabajo?</h2>
                        <a class="btn btn-outline-light btn-lg px-5 py-3 fs-6 fw-bolder" href="{% url "portafolio:contacto" %}">Contactame</a>
                    </div>
                </div>
            </section>
        </main>
        <!-- Footer-->
        {% include "blocks/footer.html" %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static "js/scripts.js" %}"></script>
    </body>
</html>